#它最后的节点是在/imu_filter_madgwick下
/imu_filter_madgwick:
  ros__parameters:
    use_mag: false    #不使用磁力计
    world_frame: enu  #ENU坐标系
    publish_tf: false #不发布tf
rtapmap:
  ros__parameters:
    approx_sync: true
    #与imu,坐标相关
    frame_id: camera_link
    wait_imu_to_init: true
    #采取的建图方式
    subscribe_depth: true
    subscribe_odom_info: true
    # visual_odometry: true
    stereo: true
    #话题参数
    depth_topic: /camera/aligned_depth_to_color/image_raw
    rgb_topic: /camera/color/image_raw
    camera_info_topic: /camera/color/camera_info
    imu_topic: /imu/data
    #调试参数
    rtabmap_args: -d --udebug
    # launch_prefix: xterm -e gdb -ex run --args