version: '3'
services:
  lio_sam_container:
    build:
      context: .
      dockerfile: Dockerfile
    image: Nagisa/lio_sam
    container_name: lio_sam_container
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - OMP_WAIT_POLICY=passive
      - TERM=xterm-256color
    volumes:
      # - ${XAUTHORITY}:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./../..:/home/Nagisa/packages
      - /dev:/dev
    network_mode: host
    pid: "host" # 添加 pid 命名空间共享
    ipc: "host" # 添加 ipc 命名空间共享    
    privileged: true
    stdin_open: true
    tty: true
    user: "Nagisa"
    #runtime: nvidia
    working_dir: "/home/Nagisa/packages/lio_sam" # 指定默认工作目录
    entrypoint: [ "/bin/bash", "-i", "-c", "/home/Nagisa/packages/lio_sam/.devcontainer/nagisa_start.sh && source ~/.bashrc && roslaunch my_lio_sam run.launch rviz:=false" ]