version: '3'
services:
  dio_slam_service:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: elainasuki/rc2025:funny_slam
    container_name: funny_slam_container
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - OMP_WAIT_POLICY=passive
      - TERM=xterm-256color
    volumes:
      # - ${XAUTHORITY}:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./../..:/home/Elaina/slam
      - /dev:/dev
    network_mode: host
    pid: "host" # 添加 pid 命名空间共享
    ipc: "host" # 添加 ipc 命名空间共享    
    privileged: true
    stdin_open: true
    tty: true
    user: "Elaina"
    # runtime: nvidia
    working_dir: "/home/Elaina/slam/funny_slam" # 指定默认工作目录
    entrypoint: [ "/bin/bash", "-i", "-c", "/home/Elaina/slam/docker_start.sh && /bin/bash" ]
