// Generated by gencpp from file funny_lidar_slam/save_map.msg
// DO NOT EDIT!


#ifndef FUNNY_LIDAR_SLAM_MESSAGE_SAVE_MAP_H
#define FUNNY_LIDAR_SLAM_MESSAGE_SAVE_MAP_H

#include <ros/service_traits.h>


#include <funny_lidar_slam/save_mapRequest.h>
#include <funny_lidar_slam/save_mapResponse.h>


namespace funny_lidar_slam
{

struct save_map
{

typedef save_mapRequest Request;
typedef save_mapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct save_map
} // namespace funny_lidar_slam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::funny_lidar_slam::save_map > {
  static const char* value()
  {
    return "6d5ba272429d8ec294f9bb44c41de2dc";
  }

  static const char* value(const ::funny_lidar_slam::save_map&) { return value(); }
};

template<>
struct DataType< ::funny_lidar_slam::save_map > {
  static const char* value()
  {
    return "funny_lidar_slam/save_map";
  }

  static const char* value(const ::funny_lidar_slam::save_map&) { return value(); }
};


// service_traits::MD5Sum< ::funny_lidar_slam::save_mapRequest> should match
// service_traits::MD5Sum< ::funny_lidar_slam::save_map >
template<>
struct MD5Sum< ::funny_lidar_slam::save_mapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::funny_lidar_slam::save_map >::value();
  }
  static const char* value(const ::funny_lidar_slam::save_mapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::funny_lidar_slam::save_mapRequest> should match
// service_traits::DataType< ::funny_lidar_slam::save_map >
template<>
struct DataType< ::funny_lidar_slam::save_mapRequest>
{
  static const char* value()
  {
    return DataType< ::funny_lidar_slam::save_map >::value();
  }
  static const char* value(const ::funny_lidar_slam::save_mapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::funny_lidar_slam::save_mapResponse> should match
// service_traits::MD5Sum< ::funny_lidar_slam::save_map >
template<>
struct MD5Sum< ::funny_lidar_slam::save_mapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::funny_lidar_slam::save_map >::value();
  }
  static const char* value(const ::funny_lidar_slam::save_mapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::funny_lidar_slam::save_mapResponse> should match
// service_traits::DataType< ::funny_lidar_slam::save_map >
template<>
struct DataType< ::funny_lidar_slam::save_mapResponse>
{
  static const char* value()
  {
    return DataType< ::funny_lidar_slam::save_map >::value();
  }
  static const char* value(const ::funny_lidar_slam::save_mapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FUNNY_LIDAR_SLAM_MESSAGE_SAVE_MAP_H
