// Generated by gencpp from file funny_lidar_slam/save_mapRequest.msg
// DO NOT EDIT!


#ifndef FUNNY_LIDAR_SLAM_MESSAGE_SAVE_MAPREQUEST_H
#define FUNNY_LIDAR_SLAM_MESSAGE_SAVE_MAPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace funny_lidar_slam
{
template <class ContainerAllocator>
struct save_mapRequest_
{
  typedef save_mapRequest_<ContainerAllocator> Type;

  save_mapRequest_()
    : map_path()
    , split_map(false)  {
    }
  save_mapRequest_(const ContainerAllocator& _alloc)
    : map_path(_alloc)
    , split_map(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _map_path_type;
  _map_path_type map_path;

   typedef uint8_t _split_map_type;
  _split_map_type split_map;





  typedef boost::shared_ptr< ::funny_lidar_slam::save_mapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::funny_lidar_slam::save_mapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct save_mapRequest_

typedef ::funny_lidar_slam::save_mapRequest_<std::allocator<void> > save_mapRequest;

typedef boost::shared_ptr< ::funny_lidar_slam::save_mapRequest > save_mapRequestPtr;
typedef boost::shared_ptr< ::funny_lidar_slam::save_mapRequest const> save_mapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::funny_lidar_slam::save_mapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::funny_lidar_slam::save_mapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::funny_lidar_slam::save_mapRequest_<ContainerAllocator1> & lhs, const ::funny_lidar_slam::save_mapRequest_<ContainerAllocator2> & rhs)
{
  return lhs.map_path == rhs.map_path &&
    lhs.split_map == rhs.split_map;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::funny_lidar_slam::save_mapRequest_<ContainerAllocator1> & lhs, const ::funny_lidar_slam::save_mapRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace funny_lidar_slam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::funny_lidar_slam::save_mapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::funny_lidar_slam::save_mapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::funny_lidar_slam::save_mapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::funny_lidar_slam::save_mapRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::funny_lidar_slam::save_mapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::funny_lidar_slam::save_mapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::funny_lidar_slam::save_mapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f03d66bf980315cf6b2f95e9e7defcf0";
  }

  static const char* value(const ::funny_lidar_slam::save_mapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf03d66bf980315cfULL;
  static const uint64_t static_value2 = 0x6b2f95e9e7defcf0ULL;
};

template<class ContainerAllocator>
struct DataType< ::funny_lidar_slam::save_mapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "funny_lidar_slam/save_mapRequest";
  }

  static const char* value(const ::funny_lidar_slam::save_mapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::funny_lidar_slam::save_mapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string map_path\n"
"bool split_map\n"
;
  }

  static const char* value(const ::funny_lidar_slam::save_mapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::funny_lidar_slam::save_mapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.map_path);
      stream.next(m.split_map);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct save_mapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::funny_lidar_slam::save_mapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::funny_lidar_slam::save_mapRequest_<ContainerAllocator>& v)
  {
    s << indent << "map_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.map_path);
    s << indent << "split_map: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.split_map);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FUNNY_LIDAR_SLAM_MESSAGE_SAVE_MAPREQUEST_H
