// Generated by gencpp from file funny_lidar_slam/save_mapResponse.msg
// DO NOT EDIT!


#ifndef FUNNY_LIDAR_SLAM_MESSAGE_SAVE_MAPRESPONSE_H
#define FUNNY_LIDAR_SLAM_MESSAGE_SAVE_MAPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace funny_lidar_slam
{
template <class ContainerAllocator>
struct save_mapResponse_
{
  typedef save_mapResponse_<ContainerAllocator> Type;

  save_mapResponse_()
    : save_map_succeed(false)
    , map_size(0)
    , map_path()  {
    }
  save_mapResponse_(const ContainerAllocator& _alloc)
    : save_map_succeed(false)
    , map_size(0)
    , map_path(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _save_map_succeed_type;
  _save_map_succeed_type save_map_succeed;

   typedef int64_t _map_size_type;
  _map_size_type map_size;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _map_path_type;
  _map_path_type map_path;





  typedef boost::shared_ptr< ::funny_lidar_slam::save_mapResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::funny_lidar_slam::save_mapResponse_<ContainerAllocator> const> ConstPtr;

}; // struct save_mapResponse_

typedef ::funny_lidar_slam::save_mapResponse_<std::allocator<void> > save_mapResponse;

typedef boost::shared_ptr< ::funny_lidar_slam::save_mapResponse > save_mapResponsePtr;
typedef boost::shared_ptr< ::funny_lidar_slam::save_mapResponse const> save_mapResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::funny_lidar_slam::save_mapResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::funny_lidar_slam::save_mapResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::funny_lidar_slam::save_mapResponse_<ContainerAllocator1> & lhs, const ::funny_lidar_slam::save_mapResponse_<ContainerAllocator2> & rhs)
{
  return lhs.save_map_succeed == rhs.save_map_succeed &&
    lhs.map_size == rhs.map_size &&
    lhs.map_path == rhs.map_path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::funny_lidar_slam::save_mapResponse_<ContainerAllocator1> & lhs, const ::funny_lidar_slam::save_mapResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace funny_lidar_slam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::funny_lidar_slam::save_mapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::funny_lidar_slam::save_mapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::funny_lidar_slam::save_mapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::funny_lidar_slam::save_mapResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::funny_lidar_slam::save_mapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::funny_lidar_slam::save_mapResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::funny_lidar_slam::save_mapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3be700429698f8fd1ee4a67715b52600";
  }

  static const char* value(const ::funny_lidar_slam::save_mapResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3be700429698f8fdULL;
  static const uint64_t static_value2 = 0x1ee4a67715b52600ULL;
};

template<class ContainerAllocator>
struct DataType< ::funny_lidar_slam::save_mapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "funny_lidar_slam/save_mapResponse";
  }

  static const char* value(const ::funny_lidar_slam::save_mapResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::funny_lidar_slam::save_mapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool save_map_succeed\n"
"int64 map_size\n"
"string map_path\n"
"\n"
"\n"
;
  }

  static const char* value(const ::funny_lidar_slam::save_mapResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::funny_lidar_slam::save_mapResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.save_map_succeed);
      stream.next(m.map_size);
      stream.next(m.map_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct save_mapResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::funny_lidar_slam::save_mapResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::funny_lidar_slam::save_mapResponse_<ContainerAllocator>& v)
  {
    s << indent << "save_map_succeed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.save_map_succeed);
    s << indent << "map_size: ";
    Printer<int64_t>::stream(s, indent + "  ", v.map_size);
    s << indent << "map_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.map_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FUNNY_LIDAR_SLAM_MESSAGE_SAVE_MAPRESPONSE_H
